### PR TITLE
Fix android build

### PR DESCRIPTION
**Pull request by ortex**
* fix jni lib name for android build
* add android stl to aar
* rename android lib module to roc-android

### CODE REVIEW

**Comment by gavv** [comment]
@MatteoArella Could you please take a look?

**Comment by MatteoArella** [comment]
LGTM :+1:

**Comment by gavv** [comment]
> LGTM +1

Great, +1 from me too. Do you have a merge button, could you merge it? (I hope I configured permissions right). Maybe you'll need to "approve" the PR first.

**Comment by MatteoArella** [comment]
> > LGTM +1
> 
> Great, +1 from me too. Do you have a merge button, could you merge it? (I hope I configured permissions right). Maybe you'll need to "approve" the PR first.

No I'm not authorized to merge it ATM.

**Comment by gavv** [comment]
Could you re-check now?

**Pull request merged**
