### PR TITLE
Android instrumented tests

### PR DESCRIPTION
**Pull request by MatteoArella**
This PR adds android instrumented tests on travis

/link #8

### CODE REVIEW

**Comment by MatteoArella** [comment]
>     https://stackoverflow.com/questions/17942819/how-can-i-get-clean-gradle-output-on-travis-ci

Nice! :+1: 

>     https://github.com/mendhak/Gradle-Travis-Colored-Output

I've already used a similar script on [build.gradle](https://github.com/roc-project/roc-java/blob/master/build.gradle#L66-L95). Anyway I've found a richer gradle plugin that we can use for styling tests [com.adarshr.test-logger](https://github.com/radarsh/gradle-test-logger-plugin).
Unfortunately all those solutions with `afterSuite` and `afterTest` hooks doesn't work for android instrumented tests; the only way for getting more infos about running tests is adding `--info --stacktrace` to gradle.

**Comment by gavv** [comment]
LGTM!

**Comment by gavv** [comment]
By the way, do you know if it's possible to run native (ELF) executables in Android simulator? It would be nice to implement the same approach in the main repo (roc-project/roc) and run our unit tests in simulator, ideally using the same java-android docker image.

**Comment by MatteoArella** [comment]
> By the way, do you know if it's possible to run native (ELF) executables in Android simulator? It would be nice to implement the same approach in the main repo (roc-project/roc) and run our unit tests in simulator, ideally using the same java-android docker image.

Yes it's possible. Just `adb push` the ELF executable into the emulator and then exec it with `adb shell`.

**Pull request merged**
