### PR TITLE
travis build

### PR DESCRIPTION
**Pull request by MatteoArella**
This PR contains:
- travis build and test on linux and osx
- travis build on android

Testing on android emulator (instrumentation testing) will be implemented on a separate PR.

Note: `roc` library cross-compiling for android on travis is actually broken on `roc` master tag due to `libuv` issue; doing `checkout` on commit `61d9cafd5e916413280dbb40f997a71ffdd28ac6` solves the issue.

### CODE REVIEW

**Comment by gavv** [comment]
Cool!

Some questions:

1. Just curious, could you clarify the difference between https://github.com/roc-project/roc-java/blob/7162469295219506e40ceafd1c0bc34bc9b2ba2d/scripts/travis/android/Dockerfile and https://github.com/roc-project/dockerfiles/blob/master/cross-aarch64-linux-android/api28/Dockerfile ?

2. I suggest to move building docker image to Docker Hub, so that travis doesn't need to build it each time and can just pull the pre-built image. You can do it by creating a PR to https://github.com/roc-project/dockerfiles. After merging it, I'll register it on Dicker Hub, and it will automatically (re)build and publish the image on GitHub push.

3. Maybe we want to create a docker image not only for cross-compiling libroc for android, but for the whole roc-java android build? I mean, we can include this:

   https://github.com/roc-project/roc-java/blob/7162469295219506e40ceafd1c0bc34bc9b2ba2d/scripts/travis/android/before_install.sh

   and this:

   https://github.com/roc-project/roc-java/blob/7162469295219506e40ceafd1c0bc34bc9b2ba2d/scripts/travis/android/env.sh

   and sdkmanager stuff from here:

   https://github.com/roc-project/roc-java/blob/7162469295219506e40ceafd1c0bc34bc9b2ba2d/scripts/travis/android/install.sh

   to the docker image as well. This way, anybody who wants to build Roc for Android can just pull this image and will get the full build environment (both for libroc and roc-java).

   What do you think?

4. Could you explain the purpose of `android/app/build.gradle`? Does it build an (empty) android app or an android library?

5. Do I understand correctly that we're duplicating build system for android, both for Java and C++ code? Is it possible to use the same build system for android and non-android builds?

   E.g., maybe always use cmake or maybe never use cmake? BTW, why do we have to use for android? IIRC, building C++ code with gradle is allowed on android too?

**Comment by gavv** [comment]
> Note: roc library cross-compiling for android on travis is actually broken on roc master tag due to libuv issue; doing checkout on commit 61d9cafd5e916413280dbb40f997a71ffdd28ac6 solves the issue.

Thanks, I'll take a look.

**Comment by gavv** [comment]
> Thanks, I'll take a look.

Could you describe the problem in more drtail?

Just checked, android build is passing on fresh master: https://travis-ci.org/github/roc-project/roc/jobs/686528260

**Comment by MatteoArella** [comment]
> Cool!
> 
> Some questions:
> 
>     1. Just curious, could you clarify the difference between https://github.com/roc-project/roc-java/blob/7162469295219506e40ceafd1c0bc34bc9b2ba2d/scripts/travis/android/Dockerfile and https://github.com/roc-project/dockerfiles/blob/master/cross-aarch64-linux-android/api28/Dockerfile ?
> 
>     2. I suggest to move building docker image to Docker Hub, so that travis doesn't need to build it each time and can just pull the pre-built image. You can do it by creating a PR to https://github.com/roc-project/dockerfiles. After merging it, I'll register it on Dicker Hub, and it will automatically (re)build and publish the image on GitHub push.
> 
>     3. Maybe we want to create a docker image not only for cross-compiling libroc for android, but for the whole roc-java android build? I mean, we can include this:
>        https://github.com/roc-project/roc-java/blob/7162469295219506e40ceafd1c0bc34bc9b2ba2d/scripts/travis/android/before_install.sh
>        and this:
>        https://github.com/roc-project/roc-java/blob/7162469295219506e40ceafd1c0bc34bc9b2ba2d/scripts/travis/android/env.sh
>        and sdkmanager stuff from here:
>        https://github.com/roc-project/roc-java/blob/7162469295219506e40ceafd1c0bc34bc9b2ba2d/scripts/travis/android/install.sh
>        to the docker image as well. This way, anybody who wants to build Roc for Android can just pull this image and will get the full build environment (both for libroc and roc-java).
>        What do you think?
> 
>     4. Could you explain the purpose of `android/app/build.gradle`? Does it build an (empty) android app or an android library?
> 
>     5. Do I understand correctly that we're duplicating build system for android, both for Java and C++ code? Is it possible to use the same build system for android and non-android builds?
>        E.g., maybe always use cmake or maybe never use cmake? BTW, why do we have to use for android? IIRC, building C++ code with gradle is allowed on android too?

1. There are mainly two differences on [https://github.com/roc-project/roc-java/blob/7162469295219506e40ceafd1c0bc34bc9b2ba2d/scripts/travis/android/Dockerfile](https://github.com/roc-project/roc-java/blob/7162469295219506e40ceafd1c0bc34bc9b2ba2d/scripts/travis/android/Dockerfile):
   - instead of the obsolete `make_standalone_toolchain.py` tool it uses ndk prebuild toolchains (located in `${NDK_DIR}/toolchains/llvm/prebuilt/linux-x86_64/bin`)
   - it prepares the toolchains for all android ABIs using the prefix format `${ARCH}-linux-android`

2. Yes it surely would reduce travis execution time. I'll do the PR soon

3. Yes it could be an easiest solution for end-user perspective. 

4. According to the first line (`apply plugin: 'com.android.library'`) it builds an android library referencing the root `roc-java` project as the source.  The `app` name is only the default name of an android project.

5. Yes they are two build systems taking both the same `sourceSet`. Unfortunately the gradle plugin for C++ projects (`cpp-library` plugin) actually doesn't cross-compile;
 the easiest solution for me, instead of reinventing from scratch a gradle plugin for both build systems, is to use a separate subproject based on `android` library plugin.

**Comment by MatteoArella** [comment]
> > Thanks, I'll take a look.
> 
> Could you describe the problem in more detail?
> 
> Just checked, android build is passing on fresh master: https://travis-ci.org/github/roc-project/roc/jobs/686528260

Yes I meant `roc` build with [https://github.com/roc-project/roc-java/blob/7162469295219506e40ceafd1c0bc34bc9b2ba2d/scripts/travis/android/Dockerfile](https://github.com/roc-project/roc-java/blob/7162469295219506e40ceafd1c0bc34bc9b2ba2d/scripts/travis/android/Dockerfile).
Here is the log of the errored `libuv` build:

````
cmake .. -DLIBUV_BUILD_TESTS=OFF -DCMAKE_FIND_ROOT_PATH=/opt/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DCMAKE_SYSROOT=/opt/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=28 -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DCMAKE_LINKER=/opt/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-clang -DCMAKE_AR=/opt/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar -DCMAKE_RANLIB=/opt/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ranlib -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS_RELEASE:STRING='-fPIC -fvisibility=hidden'

CMake Warning at /usr/share/cmake-3.13/Modules/Platform/Android-Determine.cmake:128 (message):

  Android: Did not detect API level from

    /opt/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin/clang

  or

    /opt/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/api-level.h

Call Stack (most recent call first):

  /usr/share/cmake-3.13/Modules/CMakeDetermineSystem.cmake:130 (include)

  CMakeLists.txt:3 (project)

-- Android: Targeting API '28' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'

-- The C compiler identification is Clang 9.0.8

-- Check for working C compiler: /opt/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin/clang

-- Check for working C compiler: /opt/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- broken

CMake Error at /usr/share/cmake-3.13/Modules/CMakeTestCCompiler.cmake:52 (message):

  The C compiler

    "/opt/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /tmp/roc/3rdparty/aarch64-linux-android/clang-9.0.8-release/build/libuv-1.35.0/src/libuv-v1.35.0/build/CMakeFiles/CMakeTmp

    

    Run Build Command:"/usr/bin/make" "cmTC_c979d/fast"

    /usr/bin/make -f CMakeFiles/cmTC_c979d.dir/build.make CMakeFiles/cmTC_c979d.dir/build

    make[1]: Entering directory '/tmp/roc/3rdparty/aarch64-linux-android/clang-9.0.8-release/build/libuv-1.35.0/src/libuv-v1.35.0/build/CMakeFiles/CMakeTmp'

    Building C object CMakeFiles/cmTC_c979d.dir/testCCompiler.c.o

    /opt/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=aarch64-none-linux-android --gcc-toolchain=/opt/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/opt/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/sysroot   -funwind-tables -no-canonical-prefixes  -g -fPIE   -o CMakeFiles/cmTC_c979d.dir/testCCompiler.c.o   -c /tmp/roc/3rdparty/aarch64-linux-android/clang-9.0.8-release/build/libuv-1.35.0/src/libuv-v1.35.0/build/CMakeFiles/CMakeTmp/testCCompiler.c

    Linking C executable cmTC_c979d

    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c979d.dir/link.txt --verbose=1

    /opt/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=aarch64-none-linux-android --gcc-toolchain=/opt/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/opt/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/sysroot -funwind-tables -no-canonical-prefixes  -g  -fPIE -pie -Wl,--gc-sections  CMakeFiles/cmTC_c979d.dir/testCCompiler.c.o  -o cmTC_c979d 

    /opt/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find crtbegin_dynamic.o: No such file or directory

    /opt/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find crtend_android.o: No such file or directory

    clang: error: linker command failed with exit code 1 (use -v to see invocation)

    make[1]: *** [CMakeFiles/cmTC_c979d.dir/build.make:87: cmTC_c979d] Error 1

    make[1]: Leaving directory '/tmp/roc/3rdparty/aarch64-linux-android/clang-9.0.8-release/build/libuv-1.35.0/src/libuv-v1.35.0/build/CMakeFiles/CMakeTmp'

    make: *** [Makefile:121: cmTC_c979d/fast] Error 2
````

**Comment by gavv** [comment]
```
instead of the obsolete make_standalone_toolchain.py tool it uses ndk prebuild toolchains (located in ${NDK_DIR}/toolchains/llvm/prebuilt/linux-x86_64/bin)

it prepares the toolchains for all android ABIs using the prefix format ${ARCH}-linux-android
```

I see. Great, then let's replace our current docker image for android with your version. When you'll prepare a PR to dockerfiles repo (with a new image for roc-java), could you please also update `cross-aarch64-linux-android` Dockerfile?

Since it's now for all ABIs, we should rename it from `cross-aarch64-linux-android` to `cross-linux-android`.

Current image is for single API (defined by docker tag), but I guess we now can make an image for all APIs too?

Do we really need this block?

```
    for f in *androideabi*; do ln -s $f ${f/androideabi/android}; done && \
    for f in *$API-clang; do ln -s $f ${f/$API/} && ln -s $f ${f/$API-clang/-gcc}; done && \
    for f in *$API-clang++; do ln -s $f ${f/$API/}; done && \
    ln -s armv7a-linux-android-clang arm-linux-android-clang && \
    ln -s armv7a-linux-android-clang++ arm-linux-android-clang++ && \
    ln -s armv7a-linux-android-gcc arm-linux-android-gcc
```

Instead of making these symlinks, can we just change the toolchain name here? https://github.com/roc-project/roc/blob/master/scripts/travis/android/aarch64-linux-android.sh#L4

I guess it'd be more convenient to support building with unmodified NDK.

**Comment by gavv** [comment]
> Yes I meant roc build with https://github.com/roc-project/roc-java/blob/7162469295219506e40ceafd1c0bc34bc9b2ba2d/scripts/travis/android/Dockerfile.

The problem is that our 3rdparty.py currently supports only standalone toolchain. I'm testing a fix now and will push it to master, so that we will support both ways.

**Comment by gavv** [comment]
> Yes they are two build systems taking both the same sourceSet. Unfortunately the gradle plugin for C++ projects (cpp-library plugin) actually doesn't cross-compile;
the easiest solution for me, instead of reinventing from scratch a gradle plugin for both build systems, is to use a separate subproject based on android library plugin.

Ah, I see. Okay, agree, let's go this way.

**Comment by gavv** [comment]
The fix is pushed to master.

**Comment by MatteoArella** [comment]
> I see. Great, then let's replace our current docker image for android with your version. When you'll prepare a PR to dockerfiles repo (with a new image for roc-java), could you please also update cross-aarch64-linux-android Dockerfile?
Since it's now for all ABIs, we should rename it from cross-aarch64-linux-android to cross-linux-android.

Yes sure.

---
> Current image is for single API (defined by docker tag), but I guess we now can make an image for all APIs too?

Yes defining `ARG`s into Dockerfile allows you to build different images for different APIs passing `--build-arg API=$API_VALUE` at build time.

---
> Do we really need this block?

    for f in *androideabi*; do ln -s $f ${f/androideabi/android}; done && \
    for f in *$API-clang; do ln -s $f ${f/$API/} && ln -s $f ${f/$API-clang/-gcc}; done && \
    for f in *$API-clang++; do ln -s $f ${f/$API/}; done && \
    ln -s armv7a-linux-android-clang arm-linux-android-clang && \
    ln -s armv7a-linux-android-clang++ arm-linux-android-clang++ && \
    ln -s armv7a-linux-android-gcc arm-linux-android-gcc

> Instead of making these symlinks, can we just change the toolchain name here? https://github.com/roc-project/roc/blob/master/scripts/travis/android/aarch64-linux-android.sh#L4
I guess it'd be more convenient to support building with unmodified NDK.

Unfortunately with unmodified NDK there are various problems:
  - for `arm` architecture instead of `*linux-android*`, the format `*linux-androideabi*` is used.
  - there are different clang compilers for each ARCH and API (`$ARCH-*$API-clang` and `$ARCH-*$API-clang++`) but other tools like `ar`, `as`, `ld` ecc... doesn't have the `$API` level; so for example using `aarch64-linux-android` will be ok for `ar`, `as`, `ld` tools but not for `clang` compiler, or viceversa using `aarch64-linux-android$API` will be ok for `clang` compiler but not for other tools.
  - for `arm` architecture `clang` compiler is identified by `armv7a` prefix while other tools have prefix `arm`.

**Comment by MatteoArella** [comment]
> The fix is pushed to master.

Great! :+1:

**Comment by gavv** [comment]
Thanks for clarifying. Let me see if we can modify our scons scripts to work with this naming scheme.

**Comment by gavv** [comment]
> Yes defining ARGs into Dockerfile allows you to build different images for different APIs passing --build-arg API=$API_VALUE at build time.

IIRC it's not possible to use ARGs on docker hub. But actually what I was meaning is to to have a single image and single tag, providing toolchains for all API levels supported by NDK, i.e. don't limit the image to a specific API level.

I guess it'd be possible if we can work with unmodified NDK.

**Comment by gavv** [comment]
I think you can keep those symlinks and continue working on PRs. And if I'll fix scons to work without symlinks, we'll remove them later.

**Comment by gavv** [comment]
> Let me see if we can modify our scons scripts to work with this naming scheme.

Done, the fix is pushed to master. We can now work without symlinks.

Example:

```
export PATH="$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH"

scons --build-3rdparty=libuv,openfec --host=aarch64-linux-android29 \
  --compiler=clang --disable-tests --disable-pulseaudio --disable-sox

scons --build-3rdparty=libuv,openfec --host=armv7a-linux-androideabi29 \
  --compiler=clang --disable-tests --disable-pulseaudio --disable-sox
```

**Comment by MatteoArella** [comment]
> > Yes defining ARGs into Dockerfile allows you to build different images for different APIs passing --build-arg API=$API_VALUE at build time.
> 
> IIRC it's not possible to use ARGs on docker hub. But actually what I was meaning is to to have a single image and single tag, providing toolchains for all API levels supported by NDK, i.e. don't limit the image to a specific API level.
> 
> I guess it'd be possible if we can work with unmodified NDK.

Passing ARGs on docker hub is achievable by docker [build hooks](https://docs.docker.com/docker-hub/builds/advanced/#build-hook-examples); anyway, yes surely having an unmodified NDK should be better

**Comment by MatteoArella** [comment]
> > Let me see if we can modify our scons scripts to work with this naming scheme.
> 
> Done, the fix is pushed to master. We can now work without symlinks.
> 
> Example:
> 
> ```
> export PATH="$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH"
> 
> scons --build-3rdparty=libuv,openfec --host=aarch64-linux-android29 \
>   --compiler=clang --disable-tests --disable-pulseaudio --disable-sox
> 
> scons --build-3rdparty=libuv,openfec --host=armv7a-linux-androideabi29 \
>   --compiler=clang --disable-tests --disable-pulseaudio --disable-sox
> ```

Great! So I remove all previous symlinks to `cross-linux-android` image keeping NDK unmodified.

**Comment by MatteoArella** [comment]
The build on travis is actually passing. Do you want that I add `master` branch travis build badge on `README.md`?
Do you suggest also to filter building only on `master` and future `develop` branches?

**Comment by gavv** [comment]
> The build on travis is actually passing.

Great! Only one small suggestion: if possible, I'd group Linux, macOS, and Android builds into three stages like we do it here: https://github.com/roc-project/roc/blob/master/.travis.yml

> Do you want that I add master branch travis build badge on README.md?

Let's do it.

> Do you suggest also to filter building only on master and future develop branches?

Up to you. One drawback of allowing other branches is that they will never be deleted from travis, even when deleted on github. (E.g. see [here](https://travis-ci.org/github/roc-project/roc/branches). All "Inactive Branches" do not exist and there is no way to hide them). On the other hand, building personal branches on CI may be handy. Though, it's also possible to use a personal fork for that.

**Comment by MatteoArella** [comment]
> Great! Only one small suggestion: if possible, I'd group Linux, macOS, and Android builds into three stages like we do it here: https://github.com/roc-project/roc/blob/master/.travis.yml

Ok I'll regroup into `Linux`, `macOS` and `Android` stages.

**Comment by gavv** [comment]
BTW, just noticed that roc tracing logs are enabled in java tests. Just FYI: they can significantly slow down execution.

**Comment by gavv** [comment]
LGTM!

**Pull request merged**
